name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vite App
        run: npm run build

      - name: Build Docker Image
        run: |
          docker build -t vite-app:${{ github.sha }} .

      - name: Login to Amazon ECR
        env:
          AWS_REGION: ap-southeast-1
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 723095751308.dkr.ecr.ap-southeast-1.amazonaws.com/haikali3/viteops

      # - name: Push Docker Image to ECR
      #   env:
      #     AWS_REGION: us-east-1
      #   run: |
      #     docker tag vite-app:${{ github.sha }} <ECR-REGISTRY-ID>.dkr.ecr.$AWS_REGION.amazonaws.com/vite-app:${{ github.sha }}
      #     docker push <ECR-REGISTRY-ID>.dkr.ecr.$AWS_REGION.amazonaws.com/vite-app:${{ github.sha }}
      # test

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Manual Approval for QA
  #       uses: hmarr/auto-approve-action@v1

  #     - name: Deploy to QA
  #       run: echo "Deploying to QA"

  #     - name: Manual Approval for UAT
  #       uses: hmarr/auto-approve-action@v1

  #     - name: Deploy to UAT
  #       run: echo "Deploying to UAT"

  #     - name: Manual Approval for Prod
  #       uses: hmarr/auto-approve-action@v1

  #     - name: Deploy to Prod
  #       run: echo "Deploying to Prod"
