name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vite App
        run: npm run build

      - name: Build Docker Image
        run: |
          docker build -t vite-app:${{ github.sha }} .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 723095751308.dkr.ecr.ap-southeast-1.amazonaws.com/haikali3/viteops

      - name: Push Docker Image to ECR
        run: |
          docker tag vite-app:${{ github.sha }} 723095751308.dkr.ecr.$AWS_REGION.amazonaws.com/haikali3/viteops:${{ github.sha }}
          docker push 723095751308.dkr.ecr.$AWS_REGION.amazonaws.com/haikali3/viteops:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Manual Approval for QA
        run: echo "Approve QA deployment in GitHub UI"

      - name: Deploy to QA
        run: echo "Deploying to QA"

      - name: Manual Approval for UAT
        run: echo "Approve UAT deployment in GitHub UI"

      - name: Deploy to UAT
        run: echo "Deploying to UAT"

      - name: Manual Approval for Prod
        run: echo "Approve Prod deployment in GitHub UI"

      - name: Deploy to Prod
        run: echo "Deploying to Prod"
